### ISSUE TITLE
Permission issue with /opt/teamcity/temp

### ISSUE THREAD

**Issue by Dimutrulkin** [JetBrains/teamcity-docker-images#1]
Hi. I found this issue: https://github.com/JetBrains/teamcity-docker-server/issues/38
In the Dockerfile there is:
VOLUME [/data/teamcity_server/datadir /opt/teamcity/logs /opt/teamcity/temp]
so, the 'chown tcuser:tcuser on /opt/teamcity/temp' does not helps.
We are trying to build image with our docker file:

FROM jetbrains/teamcity-server:2020.1.2
RUN mkdir /opt/teamcity/temp2
RUN chown -R tcuser:tcuser /opt/teamcity/temp2

and use the env in deployment yaml:

env:
- name: TEAMCITY_TEMP
   value: "/opt/teamcity/temp2"

but it does not helps:

[2020-07-30 05:40:23,201]   INFO -  jetbrains.buildServer.STARTUP - ===========================================================
[2020-07-30 05:40:23,201]   INFO -  jetbrains.buildServer.STARTUP - Starting TeamCity server
[2020-07-30 05:40:23,606]   INFO -  jetbrains.buildServer.STARTUP - TeamCity version: 2020.1.2 (build 78726), data format version 929
[2020-07-30 05:40:23,624]   INFO -  jetbrains.buildServer.STARTUP - OS: Linux, version 3.10.0-957.el7.x86_64, amd64, Current user: tcuser, Time zone: GMT (UTC)
[2020-07-30 05:40:23,624]   INFO -  jetbrains.buildServer.STARTUP - Java: 11.0.7, OpenJDK 64-Bit Server VM (11.0.7+10-LTS, mixed mode), OpenJDK Runtime Environment (11.0.7+10-LTS), Amazon.com Inc.; JVM parameters: --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Djava.util.logging.config.file=/opt/teamcity/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Xmx2g -XX:ReservedCodeCacheSize=350m -Dteamcity.configuration.path=../conf/teamcity-startup.properties -Dlog4j.configuration=file:/opt/teamcity/bin/../conf/teamcity-server-log4j.xml -Dteamcity_logs=/opt/teamcity/bin/../logs -Djava.awt.headless=true -Dignore.endorsed.dirs= -Dcatalina.base=/opt/teamcity -Dcatalina.home=/opt/teamcity -Djava.io.tmpdir=/opt/teamcity/temp
[2020-07-30 05:40:23,625]   INFO -  jetbrains.buildServer.STARTUP - Garbage collection: Copy, MarkSweepCompact
[2020-07-30 05:40:23,625]   INFO -  jetbrains.buildServer.STARTUP - Web server version: Apache Tomcat/8.5.54
[2020-07-30 05:40:23,626]   INFO -  jetbrains.buildServer.STARTUP - Server IP address: 10.233.102.19
[2020-07-30 05:40:23,630]   INFO -  jetbrains.buildServer.STARTUP - Web server ports: 8111 (protocol: HTTP/1.1, scheme: http), 8105 (shutdown port)
[2020-07-30 05:40:23,630]   INFO -  jetbrains.buildServer.STARTUP - Context path: "/", servlet real path: "/opt/teamcity/webapps/ROOT"
[2020-07-30 05:40:23,639]   INFO -  jetbrains.buildServer.STARTUP - TeamCity distribution type: docker-ubuntu
[2020-07-30 05:40:23,639]   INFO -  jetbrains.buildServer.STARTUP - TeamCity server node id: MAIN_SERVER
[2020-07-30 05:40:23,644]  ERROR -  jetbrains.buildServer.STARTUP - It seems the directory (/opt/teamcity/temp) is not writable. TeamCity requires it to be writable.

env:

tcuser@teamcity-server-7d7649bbd4-7gm4d:/$ env
TEAMCITY_SERVER_PORT=tcp://10.233.6.210:8111
LC_ALL=en_US.UTF-8
POSTGRES_SERVICE_PORT=5432
TEAMCITY_SERVER_PORT_8111_TCP_PROTO=tcp
LANG=C.UTF-8
TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
HOSTNAME=teamcity-server-7d7649bbd4-7gm4d
TEAMCITY_TEMP=/opt/teamcity/temp2

is there any workaround?

**Comment by Amousy** [comment]
Hello, I had the same problem when upgrading to version 2020.2.1.
"Permission problem: CATALINA_TMPDIR '/opt/teamcity/temp' is not a writeable directory"

**Comment by kir** [comment]
@Dimutrulkin Starting with TeamCity 2020.2.1 TeamCity uses environment variable `$CATALINA_TMPDIR` to specify the temp directory. Not the `TEAMCITY_TEMP`. CATALINA_TMPDIR is a standard variable for Tomcat, and TeamCity uses Tomcat under the hood.

Would it help?

**Comment by kir** [comment]
@Amousy Please check the whole error message - it should contain instructions how to fix the issue. Please let me know if this is unclear.

Best,

**Comment by Amousy** [comment]
Hi @kir, thanks for your reply.
I applied the fix: run 'chown -R 1000:1000' on the corresponding volume but it doesn't work.
However, for volumes /data/teamcity_server/datadir and /opt/teamcity/logs the chown command solved the problem.

**Comment by kir** [comment]
Hi @Amousy ,

 Could you please tell how exactly do you start the teamcity-server? What is the command line for that?
  
 Thanks,

**Comment by Amousy** [comment]
I use docker-compose command on a vm centos with the following file:
version: "3"
services:
   teamcity:
      image: jetbrains/teamcity-server:latest
      expose:
         - "8111"
      volumes:
         - "/data/teamcity/data:/data/teamcity_server/datadir"
         - "/data/teamcity/logs:/opt/teamcity/logs"
         - "/data/teamcity/temp:/opt/teamcity/temp"
   nginx:
      image: nginx:alpine
      depends_on:
         - teamcity
      ports:
         - "80:80"
         - "443:443"

**Comment by kir** [comment]
Looks fine, if /data/teamcity/temp is owned and writable by 1000:1000 user. What is the `ls -la /data/teamcity/temp` output?

**Comment by Cereal2nd** [comment]
we have the exact same problem

```
root@tda:/srv/teamcity# docker-compose up server
Starting teamcity_server_1 ... done
Attaching to teamcity_server_1
server_1  | /run-services.sh
server_1  | /services/check-server-volumes.sh
server_1  |
server_1  | >>> Permission problem: CATALINA_TMPDIR '/opt/teamcity/temp' is not a writeable directory
server_1  |
server_1  |     Looks like some mandatory directories are not writable (see above).
server_1  |     TeamCity container is running under 'tcuser' (1000/1000) user.
server_1  |
server_1  |     A quick workaround: pass '-u 0' parameter to 'docker run' command to start it under 'root' user.
server_1  |     The proper fix: run 'chown -R 1000:1000' on the corresponding volume(s), this can take noticeable time.
server_1  |
teamcity_server_1 exited with code 1
root@tda:/srv/teamcity# cat docker-compose.yml
version: "3"
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
      - ./tmp_dir:/opt/teamcity/temp
  agent1:
    build: agent
    restart: always
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent1
  agent2:
    build: agent
    restart: always
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent2
  agent3:
    build: agent
    restart: always
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent3
root@tda:/srv/teamcity# id nelosadmin
uid=1000(nelosadmin) gid=1000(nelosadmin) groups=1000(nelosadmin),27(sudo)
root@tda:/srv/teamcity# ls -al
total 36
drwxr-xr-x 6 root       root        4096 Jan  6 10:41 .
drwxr-xr-x 6 root       root        4096 Jul 29 12:30 ..
drwxr-xr-x 2 root       root        4096 Jul  2  2020 agent
drwxr-xr-x 7 nelosadmin nelosadmin  4096 Jan  6 10:41 data_dir
-rw-r--r-- 1 root       root         621 Jan  6 10:41 docker-compose.yml
drwxr-xr-x 2 nelosadmin nelosadmin 12288 Jan  6 10:41 log_dir
drwsrwsrwt 2 nelosadmin nelosadmin  4096 Jan  6 10:33 tmp_dir

```

**Comment by kir** [comment]
Hello @Cereal2nd ,

  Thanks for the details. Could you please run `sudo docker images |grep jetbrains/teamcity-server` ?
  I've just checked your scenario on Ubuntu 20 and it worked for me, with image ID a9a8c92c3a31.

  Thanks,

**Comment by Cereal2nd** [comment]
```
root@tda:/home/nelosadmin# docker images |grep jetbrains/teamcity-server
jetbrains/teamcity-server                latest              a9a8c92c3a31        3 weeks ago         2.06GB
```

**Comment by kir** [comment]
Hmm. What is the OS and the docker version?

**Comment by Cereal2nd** [comment]
```
root@tda:/srv/teamcity# cat /etc/debian_version
9.13
root@tda:/srv/teamcity# docker -v
Docker version 19.03.13, build 4484c46d9d
```

**Comment by Amousy** [comment]
Hi @kir,
the output of ls -la /data/teamcity is 
total 32
drwxrwxrwx. 5 gke-0fcb45f5b02398295645 google-sudoers  4096 Jan  5 15:04 .
drwxrwxrwx. 5 root                     root            4096 Sep 23 21:30 ..
drwxrwxrwx. 8 gke-0fcb45f5b02398295645 google-sudoers  4096 Jan  5 15:12 data
drwxrwxrwx. 3 gke-0fcb45f5b02398295645 google-sudoers 16384 Jan  5 15:12 logs
drwxrwxrwx. 2 gke-0fcb45f5b02398295645 google-sudoers  4096 Jan  5 15:04 temp

and I'm using image ID a9a8c92c3a31.

OS version: centos-release-7-8.2003.0.el7.centos.x86_64
Docker version: Docker version 19.03.13, build 4484c46d9d
Docker compose version: docker-compose version 1.27.3, build 4092ae5d

**Comment by renjinsk** [comment]
Same problem here but with AWS CloudFormation template.
Any ideas where I can find the `/data/teamcity_server` folder in the host machine?
There is nothing `/opt` folder apart from an `aws/` folder.
And nothing under `/mnt` folder (as seen from the mount points)

**Comment by kir** [comment]
Could you please run the commands like:

```
export TC_TMP=/home/vagrant/teamcity-server/tmp_dir
sudo docker run -ti -v $TC_TMP:/opt/teamcity/temp jetbrains/teamcity-server bash
ls -ld /opt/teamcity/temp 
sh /services/check-server-volumes.sh
```

Would it show the error?

**Comment by kir** [comment]
@renjinsk I'm not sure about AWS CloudFormation template. `logs/teamcity/` and `temp/teamcity/` should be chowned to uid 1000. Does the error message mention TeamCity data directory as well?

**Comment by renjinsk** [comment]
@kir This is the cloudwatch log
```
mkdir: cannot create directory ‘/data/teamcity_server/datadir/lib’: Permission denied
--
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: central.maven.org
mkdir: cannot create directory ‘/data/teamcity_server/datadir/config’: Permission denied
/bin/bash: /data/teamcity_server/datadir/config/database.properties: No such file or directory
/bin/bash: /data/teamcity_server/datadir/config/database.properties: No such file or directory
/bin/bash: /data/teamcity_server/datadir/config/database.properties: No such file or directory
mkdir: cannot create directory ‘/data/teamcity_server/datadir/plugins’: Permission denied
% Total    % Received % Xferd  Average Speed   Time    Time     Time  CurrentCopy  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
Warning: /data/teamcity_server/datadir/plugins/aws-ecs.zip: No such file or
Warning: directory
0 9364k    0 15827    0     0  89926      0  0:01:46 --:--:--  0:01:46 89926
curl: (23) Failed writing body (0 != 15827)
/run-services.sh
/services/check-server-volumes.sh
>>> Permission problem: TEAMCITY_DATA_PATH '/data/teamcity_server/datadir' is not a writeable directory
>>> Permission problem: TEAMCITY_LOGS '/opt/teamcity/logs' is not a writeable directory
>>> Permission problem: CATALINA_TMPDIR '/opt/teamcity/temp' is not a writeable directory
Looks like some mandatory directories are not writable (see above).
TeamCity container is running under 'tcuser' (1000/1000) user.
A quick workaround: pass '-u 0' parameter to 'docker run' command to start it under 'root' user.
The proper fix: run 'chown -R 1000:1000' on the corresponding volume(s), this can take noticeable time.
```

**Comment by kir** [comment]
@renjinsk Probably for you the easiest fix would be to pass User: "root" to the AWS template definition, as described here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-user

TeamCity AWS Template has a couple of `ContainerDefinitions:` sections and this User option should be added there, I think. 

Hope this helps,

**Comment by kir** [comment]
@Cereal2nd @Amousy Also, could you please check the contents of the corresponding `temp` folders with `ls -la` command and ensure that they don't contain any files, including those starting with `.`

HTH,

**Comment by renjinsk** [comment]
> @renjinsk Probably for you the easiest fix would be to pass User: "root" to the AWS template definition, as described here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-user
> 
> TeamCity AWS Template has a couple of `ContainerDefinitions:` sections and this User option should be added there, I think.
> 
> Hope this helps,

Well, that fixed the issue... 
Thank you very much!  
Although I find it a bit "dirty"

**Comment by Amousy** [comment]
Hi @kir,
Here is the result below.
$ export TC_TMP=/home/vagrant/teamcity-server/tmp_dir
$ sudo docker run -ti -v $TC_TMP:/opt/teamcity/temp jetbrains/teamcity-server bash
   Welcome to TeamCity Server Docker container
 * Installation directory: /opt/teamcity
 * Logs directory:         /opt/teamcity/logs
 * Data directory:         /data/teamcity_server/datadir
   TeamCity will be running under 'tcuser' user (1000/1000)
tcuser@e5ba52e043ea:/$ ls -laR /opt/teamcity/temp 
/opt/teamcity/temp:
total 0
drwxr-xr-x. 2 root   root    6 Jan  7 10:33 .
drwxr-xr-x. 1 tcuser tcuser 21 Dec 15 18:38 ..
tcuser@e5ba52e043ea:/$ sh /services/check-server-volumes.sh
>>> Permission problem: CATALINA_TMPDIR '/opt/teamcity/temp' is not a writeable directory
    Looks like some mandatory directories are not writable (see above).
    TeamCity container is running under 'tcuser' (1000/1000) user.
    A quick workaround: pass '-u 0' parameter to 'docker run' command to start it under 'root' user.
    The proper fix: run 'chown -R 1000:1000' on the corresponding volume(s), this can take noticeable time.

**Comment by kir** [comment]
@Amousy Could you please correct the path at `TC_TMP=/home/vagrant/teamcity-server/tmp_dir` to point to temp directory on your machine owned by user 1000.

**Comment by Amousy** [comment]
I found the source of the problem!
The temp volume was bound by an old container and docker did not see the rights update on temp folder.
A little "docker container prune" and the case is solved.

Sorry for the inconvenience.

**Comment by kir** [comment]
Hello @Amousy ,

  Thanks a lot for letting me know! We'll alter the message text to mention such a scenario.
  Hope this will fix the issue for @Cereal2nd as well.

  Have a nice day :)

**Comment by Cereal2nd** [comment]
the prune also solved my problems.
thanks a lot
