### ISSUE TITLE
MinimalAgent dockerfile accessing /opt/buildagent/system/.teamcity-agent without creating it

### ISSUE THREAD

**Issue by tbp105** [JetBrains/teamcity-docker-images#10]
The Dockerfile for the MinimalAgent does a "mkdir -p /opt/buildagent/system" but should be doing "mkdir -p /opt/buildagent/system/.teamcity-agent" instead, since that's the directory the sed command is referencing.

**Comment by hopix** [comment]
Hit the same issue when try to build `generated/linux/MinimalAgent/Ubuntu/20.04/Dockerfile`.

**Comment by NikolayPianikov** [comment]
@tbp105 @hopix thanks
