### ISSUE TITLE
UI show "[an error occurred while processing the directive]"

### ISSUE THREAD

**Issue by shenqinb** [JetBrains/teamcity-docker-images#11]
after I deployed the teamcity-server image (jetbrains/teamcity-server:2020.1.5-linux) to kubernetes environment, I see a lot of **[an error occurred while processing the directive]** errors in the TeamCity UI.

![image](https://user-images.githubusercontent.com/5157526/99084932-88180e00-2602-11eb-85a6-af5dac2853c4.png)

**Comment by kir** [comment]
Please create a more detailed issue at https://youtrack.jetbrains.com/newIssue?project=TW , thanks!
