### ISSUE TITLE
Request about linux-sudo images

### ISSUE THREAD

**Issue by u1-liquid** [JetBrains/teamcity-docker-images#12]
From cfddd6d0c7ef857509e32d41cc483897ed8142e0 , Images tagged 'latest' does NOT including docker support.
But I can't find any mentitons about this from [Upgrade Notes](https://www.jetbrains.com/help/teamcity/upgrade-notes.html#Changes+from+2020.1.x+to+2020.2).

The updated document recommands 'linux-sudo' image now, 
so I think the current 'latest' should be replaced the 'linux-sudo' image for compatibility,
Or at least 'latest-linux-sudo' tag should be provided for support scripted upgrade for agent.

**Comment by burnasheva** [comment]
Hi, @u1-liquid. I created the issue in YouTrack - please, check the progress there - https://youtrack.jetbrains.com/issue/TW-69024.
