### ISSUE TITLE
2020.2.1 startup failure (Permission problem)

### ISSUE THREAD

**Issue by seregamorph** [JetBrains/teamcity-docker-images#13]
My docker-compose looks like
```yaml
version: '3'

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    restart: unless-stopped
    ports:
      - 8111:8111
    volumes:
      - /home/ubuntu/teamcity/data:/data/teamcity_server/datadir
      - /home/ubuntu/teamcity/logs:/opt/teamcity/logs
```

With the latest tag `2020.2.1` there is a startup issue:
```
docker-compose pull
docker-compose up -d
docker logs -f teamcity-server
```
In logs I see repeated:
```
/run-services.sh
/services/check-server-volumes.sh

>>> Permission problem: TEAMCITY_DATA_PATH '/data/teamcity_server/datadir' is not a writeable directory
>>> Permission problem: TEAMCITY_LOGS '/opt/teamcity/logs' is not a writeable directory

    Looks like some mandatory directories are not writable (see above).
    TeamCity container is running under 'tcuser' (1000/1000) user.

    A quick workaround: pass '-u 0' parameter to 'docker run' command to start it under 'root' user.
    The proper fix: run 'chown -R 1000:1000' on the corresponding volume(s), this can take noticeable time.
```

Please note, that I've used exactly the same docker-compose for a long time and earlier there were no problem. If explicitly previous tag `2020.2` is set, everything is fine.

I've checked directory permissions, they seem to be the fine. I even tried from scratch (`/home/ubuntu/teamcity` does not exist) and there is the same failure. As a workaround I have to stay on 2020.2.

**Comment by seregamorph** [comment]
OMG something wrong with my eyes. Just followed advice with `chown`, now it's fine.
So is it desired behaviour? Minor update breaks major installation?

**Comment by burnasheva** [comment]
Hi, @seregamorph. 
Yes, this is the expected behavior, please, check [the upgrade notes](https://www.jetbrains.com/help/teamcity/upgrade-notes.html#Breaking+change+for+Linux+Docker+images+of+TeamCity+Server%3A+non-root+user+by+default). Also, [here](https://youtrack.jetbrains.com/issue/TW-66361) the related issue in YouTrack. 
As the workaround is pretty easy and this isn't related to the server itself we decided to not wait until the next major release.
