### ISSUE TITLE
How to set registry mirror?

### ISSUE THREAD

**Issue by lawrenceching** [JetBrains/teamcity-docker-images#18]
Hi,

I'm looking for a way to set mirror urls when DOCKER_IN_DOCKER is enabled.
It seems that there is no variable like DOCKER_OPTS or DOCKER_MIRROR I can set.
However, I'm running teamcity agent in my company. Pulling image from internal mirror server is a must.

Thanks in advance.

**Comment by kir** [comment]
Hello, sorry for the delay with the answer.
I've created an issue for this problem, please vote/watch: https://youtrack.jetbrains.com/issue/TW-71633
