### ISSUE TITLE
Environment variable for /opt/buildagent folder path

### ISSUE THREAD

**Issue by oakio** [JetBrains/teamcity-docker-images#5]
It would be nice has environment variable for `/opt/buildagent` folder path for this case:

> The problem is, that multiple agent containers would use the same (/opt/buildagent/*) directories as they are mounted from the host machine to the agent container and that the docker wrapper mounts the directories from the host to the nested docker wrapper container. And, you cannot use multiple agent containers with different paths on the host as the docker wrapper would still try to map the paths as they are in the agent container, but from the host machine to the nested docker wrapper container. To make several agents work with docker wrapper and docker.sock option, one have to build different teamcity-agent docker images with different paths of teamcity-agent installation inside those images (like /opt/buildagentN), and start those images with corresponding parameters like -v /opt/buildagent1/work:/opt/buildagent1/work etc. [source](https://hub.docker.com/r/jetbrains/teamcity-agent/)

**Comment by kir** [comment]
Hi, 

  If you follow this path, you should create docker images yourself. And when starting a docker-container from the image, you can pass an environment variable with this path when starting this container via -e key. So at least this may serve as a workaround. Would it?

  Regards,

**Comment by oakio** [comment]
Create new docker image yourself not convenient (you should build, store and periodically update for security reasons this image).
Why not add this variable by analogy with `AGENT_NAME` or `OWN_PORT`.

**Comment by kir** [comment]
The AGENT_NAME and OWN_PORT are runtime parameters, can be easily specified in the command line.
 
The installation of the build agent is build-time parameter. It is probably overkill to copy a build agent into a new location on disk each time docker container is started, depending on container parameters.

**Comment by oakio** [comment]
OK, I understood you, for build-time parameter this is really impossible.
