### ISSUE TITLE
 Server should log to stdout by default

### ISSUE THREAD

**Issue by flaw** [JetBrains/teamcity-docker-images#6]
See the issue from the deprecated repositoy: https://github.com/JetBrains/teamcity-docker-server/issues/16

In general it is good practice for Docker containers to output relevant logs on stdout instead of a file inside the container. Files inside a container make it really difficult to utilize a central log management platform. 
We just lost the log files from a critical teamcity crash due to the log files rolling over before we managed to respond. We can see from our Kubernetes logs that TeamCity started responding with 504 for no apparent reason in the middle of the night but can't actually link that with the relevant lines from TeamCity logs. 
This could've been completely avoided were we able to ingest TeamCity logs like we do all other logs.

**Comment by kir** [comment]
Filed as https://youtrack.jetbrains.com/issue/TW-67552
