### ISSUE TITLE
Connecting to Teamcity Cloud

### ISSUE THREAD

**Issue by maxhayward** [JetBrains/teamcity-docker-images#7]
I recently created a new Teamcity Cloud Beta account.

When launching the Docker Teamcity Build Agent, it attempts to connect to Teamcity Cloud on port 9090, which is not open. 

a) How can I point the Docker Agent to a different port?
b) What is the correct port to use for connecting an Agent to Teamcity Cloud?

**Comment by kir** [comment]
Thanks for your patience :) 

> When launching the Docker Teamcity Build Agent, it attempts to connect to Teamcity Cloud on port 9090, which is not open.

As per the [docs](https://hub.docker.com/repository/docker/jetbrains/teamcity-agent), you should specify your server URL via SERVER_URL environment variable. Have you done this?

Could you give some more details on the problem you've faced?

Thanks,
