### ISSUE TITLE
Feature Request: Support ARM64 architecture

### ISSUE THREAD

**Issue by funnybirdman** [JetBrains/teamcity-docker-images#9]
We would like to use a raspberry-pi 4 as a build agent.

```
 docker pull jetbrains/teamcity-agent

Using default tag: latest
latest: Pulling from jetbrains/teamcity-agent
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by vlobachev** [comment]
Also interested in this image.

**Comment by vlobachev** [comment]
If you are interested in this feature, please vote for it: https://youtrack.jetbrains.com/issue/TW-68887

**Comment by NikolayPianikov** [comment]
Fixed

You could build images using:
- https://github.com/JetBrains/teamcity-docker-images/blob/master/generated/teamcity-server-local-linux-arm64-20.04.sh
- https://github.com/JetBrains/teamcity-docker-images/blob/master/generated/teamcity-minimal-agent-local-linux-arm64-20.04.sh
- and [this guide](https://github.com/JetBrains/teamcity-docker-images#to-build-docker-images-that-were-not-provided-in-docker-repositories-you-could-generate-them-by-yourself)
